-- Primera migración Flyway del proyecto (antes de esto, el esquema lo creaba
-- Hibernate con ddl-auto=update — ver 06-database/migrations.md).
--
-- Todo el archivo usa IF NOT EXISTS para funcionar correctamente en los DOS
-- escenarios posibles:
--
--  1. Base de datos NUEVA (docker compose down -v && up, o un entorno recién
--     clonado): ninguna tabla existe todavía → los CREATE TABLE de abajo
--     crean el esquema completo tal como lo generan las entidades hoy
--     (incluyendo group_members.role, users.pending_email y admin_audit_log).
--
--  2. Base de datos EXISTENTE (el dev local de cualquiera que venga usando
--     ddl-auto=update hasta ahora): baseline-on-migrate=true (ver
--     application.properties) hace que Flyway marque el esquema actual como
--     "ya migrado" en vez de intentar recrearlo — pero V1 igual SE EJECUTA
--     contra esa base (solo se saltea el baseline, no las migraciones reales
--     posteriores a baseline-version). Ahí los CREATE TABLE IF NOT EXISTS son
--     no-op (ya existen) y lo único que corre de verdad son los ALTER TABLE
--     ADD COLUMN IF NOT EXISTS de group_members/users y el CREATE TABLE de
--     admin_audit_log (que sí es nuevo en ambos escenarios).
--
-- DDL verificado contra un volcado real (pg_dump --schema-only) de una base
-- creada desde cero por Hibernate con las entidades actuales — no es DDL
-- escrito a mano sin contrastar.

-- ─── admin_audit_log ─────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.admin_audit_log (
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action           character varying(20) NOT NULL
                     CONSTRAINT admin_audit_log_action_check
                     CHECK (action IN ('BAN','ACTIVATE','DELETE','ROLE_CHANGE')),
    actor_id         bigint NOT NULL,
    actor_username   character varying(50) NOT NULL,
    created_at       timestamp(6) without time zone,
    details          character varying(500),
    target_id        bigint NOT NULL,
    target_username  character varying(50) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_audit_log_actor   ON public.admin_audit_log USING btree (actor_id);
CREATE INDEX IF NOT EXISTS idx_audit_log_created ON public.admin_audit_log USING btree (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_audit_log_target  ON public.admin_audit_log USING btree (target_id);

-- ─── app_config ──────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.app_config (
    config_key    character varying(100) NOT NULL PRIMARY KEY,
    description   character varying(255),
    updated_at    timestamp(6) without time zone,
    updated_by    bigint,
    config_value  character varying(500) NOT NULL
);

-- ─── blocked_users ───────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.blocked_users (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    blocked_id  bigint NOT NULL,
    blocker_id  bigint NOT NULL,
    created_at  timestamp(6) without time zone,
    CONSTRAINT uk_blocked_pair UNIQUE (blocker_id, blocked_id)
);

CREATE INDEX IF NOT EXISTS idx_blocked_blocked ON public.blocked_users USING btree (blocked_id);
CREATE INDEX IF NOT EXISTS idx_blocked_blocker ON public.blocked_users USING btree (blocker_id);

-- ─── conversations ───────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.conversations (
    id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by              bigint,
    ephemeral_enabled       boolean DEFAULT false NOT NULL,
    group_avatar            character varying(500),
    group_name              character varying(100),
    last_message_at         timestamp(6) without time zone,
    last_message_preview    character varying(50),
    last_message_sender_id  bigint,
    muted_user1             boolean NOT NULL,
    muted_user2             boolean NOT NULL,
    status                  character varying(20) NOT NULL
                            CONSTRAINT conversations_status_check
                            CHECK (status IN ('ONLINE','TYPING','OFFLINE','AWAY')),
    type                    character varying(20) DEFAULT 'DIRECT' NOT NULL
                            CONSTRAINT conversations_type_check
                            CHECK (type IN ('DIRECT','GROUP')),
    unread_count_user1      integer NOT NULL,
    unread_count_user2      integer NOT NULL,
    updated_at              timestamp(6) without time zone,
    user1_avatar            character varying(500),
    user1_id                bigint,
    user1_username          character varying(50),
    user2_avatar            character varying(500),
    user2_id                bigint,
    user2_username          character varying(50),
    CONSTRAINT uk_conv_participants UNIQUE (user1_id, user2_id)
);

CREATE INDEX IF NOT EXISTS idx_conv_user1 ON public.conversations USING btree (user1_id, last_message_at DESC);
CREATE INDEX IF NOT EXISTS idx_conv_user2 ON public.conversations USING btree (user2_id, last_message_at DESC);

-- ─── group_members (ya incluye "role" para una base nueva) ──────────────
CREATE TABLE IF NOT EXISTS public.group_members (
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    avatar           character varying(500),
    conversation_id  bigint NOT NULL,
    joined_at        timestamp(6) without time zone,
    muted            boolean NOT NULL,
    role             character varying(20) NOT NULL DEFAULT 'MEMBER'
                     CONSTRAINT group_members_role_check
                     CHECK (role IN ('OWNER','ADMIN','MEMBER')),
    unread_count     integer NOT NULL,
    user_id          bigint NOT NULL,
    username         character varying(50) NOT NULL,
    CONSTRAINT uk_group_members_conv_user UNIQUE (conversation_id, user_id)
);

CREATE INDEX IF NOT EXISTS idx_group_members_conversation ON public.group_members USING btree (conversation_id);
CREATE INDEX IF NOT EXISTS idx_group_members_user         ON public.group_members USING btree (user_id);

-- Base EXISTENTE: agrega "role" si la tabla ya existía sin esta columna.
-- El creador de cada grupo (conversations.created_by) pasa a OWNER; el resto queda MEMBER.
ALTER TABLE public.group_members ADD COLUMN IF NOT EXISTS role character varying(20);

UPDATE public.group_members gm
SET role = CASE WHEN gm.user_id = c.created_by THEN 'OWNER' ELSE 'MEMBER' END
FROM public.conversations c
WHERE c.id = gm.conversation_id
  AND gm.role IS NULL;

UPDATE public.group_members SET role = 'MEMBER' WHERE role IS NULL; -- filas huérfanas, no debería pasar

ALTER TABLE public.group_members ALTER COLUMN role SET DEFAULT 'MEMBER';
ALTER TABLE public.group_members ALTER COLUMN role SET NOT NULL;

DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'group_members_role_check') THEN
        ALTER TABLE public.group_members
            ADD CONSTRAINT group_members_role_check CHECK (role IN ('OWNER','ADMIN','MEMBER'));
    END IF;
END $$;

-- ─── messages ────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.messages (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_message_id   character varying(64),
    conversation_id     bigint NOT NULL,
    deleted             boolean NOT NULL,
    edited_at           timestamp(6) without time zone,
    expires_at          timestamp(6) without time zone,
    file_urls           jsonb,
    payload             jsonb,
    payload_type        character varying(20)
                        CONSTRAINT messages_payload_type_check
                        CHECK (payload_type IN ('SALES','SYSTEM','SURVEY','CARD')),
    read_at             timestamp(6) without time zone,
    receiver_id         bigint,
    sender_id           bigint NOT NULL,
    sent_at             timestamp(6) without time zone,
    status              character varying(20) NOT NULL
                        CONSTRAINT messages_status_check
                        CHECK (status IN ('SENT','DELIVERED','READ')),
    text_content        text,
    type                character varying(20) NOT NULL
                        CONSTRAINT messages_type_check
                        CHECK (type IN ('TEXT','PAYLOAD','FILE','IMAGE','AUDIO')),
    CONSTRAINT ukk6x4jae1y4fstteqf7qno19q8 UNIQUE (client_message_id)
);

CREATE INDEX IF NOT EXISTS idx_msg_conv_recv_status ON public.messages USING btree (conversation_id, receiver_id, status);
CREATE INDEX IF NOT EXISTS idx_msg_conversation     ON public.messages USING btree (conversation_id, id DESC);
CREATE INDEX IF NOT EXISTS idx_msg_sender           ON public.messages USING btree (sender_id);
CREATE INDEX IF NOT EXISTS idx_msg_status           ON public.messages USING btree (status);

-- ─── streaks ─────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.streaks (
    id                     bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id        bigint NOT NULL,
    current_count          integer NOT NULL,
    enabled                boolean NOT NULL,
    last_interaction_date  date,
    last_message_date_a    date,
    last_message_date_b    date,
    longest_count          integer NOT NULL,
    request_status         character varying(20) NOT NULL
                           CONSTRAINT streaks_request_status_check
                           CHECK (request_status IN ('NONE','PENDING','ACCEPTED','DECLINED')),
    requested_by_user_id   bigint,
    status                 character varying(20) NOT NULL
                           CONSTRAINT streaks_status_check
                           CHECK (status IN ('INACTIVE','ACTIVE','AT_RISK','BROKEN')),
    updated_at             timestamp(6) without time zone,
    user_a_id              bigint NOT NULL,
    user_b_id              bigint NOT NULL,
    version                bigint,
    CONSTRAINT uk_streak_conversation UNIQUE (conversation_id)
);

-- ─── users (ya incluye "pending_email" para una base nueva) ─────────────
CREATE TABLE IF NOT EXISTS public.users (
    id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    auth_provider     character varying(20) DEFAULT 'LOCAL' NOT NULL
                      CONSTRAINT users_auth_provider_check
                      CHECK (auth_provider IN ('LOCAL','GOOGLE')),
    avatar            character varying(500),
    created_at        timestamp(6) without time zone,
    dni               character varying(20),
    email             character varying(120) NOT NULL,
    google_id         character varying(50),
    otp_code          character varying(6),
    otp_expiration    timestamp(6) without time zone,
    password          character varying(255),
    pending_email     character varying(120),
    phone             character varying(20),
    role              character varying(20) NOT NULL
                      CONSTRAINT users_role_check
                      CHECK (role IN ('USER','ADMIN','SUPERADMIN')),
    status            character varying(30) NOT NULL
                      CONSTRAINT users_status_check
                      CHECK (status IN ('PENDING_VERIFICATION','ACTIVE','BANNED','INACTIVE','DELETED')),
    theme_preference  character varying(10) DEFAULT 'LIGHT' NOT NULL
                      CONSTRAINT users_theme_preference_check
                      CHECK (theme_preference IN ('LIGHT','DARK')),
    updated_at        timestamp(6) without time zone,
    updated_by        bigint,
    username          character varying(50) NOT NULL,
    username_lower    character varying(50) NOT NULL,
    CONSTRAINT uk_users_dni UNIQUE (dni),
    CONSTRAINT uk_users_email UNIQUE (email),
    CONSTRAINT uk_users_google_id UNIQUE (google_id),
    CONSTRAINT uk_users_username UNIQUE (username)
);

CREATE INDEX IF NOT EXISTS idx_users_username_lower ON public.users USING btree (username_lower);

-- Base EXISTENTE: agrega "pending_email" si la tabla ya existía sin esta columna.
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS pending_email character varying(120);
